/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const ProfitCalculation = IDL.Record({
  'profitLossAmount' : IDL.Float64,
  'isProfit' : IDL.Bool,
  'profitLossPercent' : IDL.Float64,
});
export const TaxCalculation = IDL.Record({
  'taxAmount' : IDL.Float64,
  'isTaxable' : IDL.Bool,
});
export const CryptoPrice = IDL.Record({
  'volume' : IDL.Float64,
  'price' : IDL.Float64,
  'changePercent' : IDL.Float64,
  'symbol' : IDL.Text,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  'calculateProfit' : IDL.Func(
      [IDL.Float64, IDL.Float64, IDL.Float64],
      [ProfitCalculation],
      ['query'],
    ),
  'calculateTax' : IDL.Func(
      [IDL.Float64, IDL.Float64],
      [TaxCalculation],
      ['query'],
    ),
  'getCryptoPrices' : IDL.Func([], [IDL.Vec(CryptoPrice)], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const ProfitCalculation = IDL.Record({
    'profitLossAmount' : IDL.Float64,
    'isProfit' : IDL.Bool,
    'profitLossPercent' : IDL.Float64,
  });
  const TaxCalculation = IDL.Record({
    'taxAmount' : IDL.Float64,
    'isTaxable' : IDL.Bool,
  });
  const CryptoPrice = IDL.Record({
    'volume' : IDL.Float64,
    'price' : IDL.Float64,
    'changePercent' : IDL.Float64,
    'symbol' : IDL.Text,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    'calculateProfit' : IDL.Func(
        [IDL.Float64, IDL.Float64, IDL.Float64],
        [ProfitCalculation],
        ['query'],
      ),
    'calculateTax' : IDL.Func(
        [IDL.Float64, IDL.Float64],
        [TaxCalculation],
        ['query'],
      ),
    'getCryptoPrices' : IDL.Func([], [IDL.Vec(CryptoPrice)], []),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
  });
};

export const init = ({ IDL }) => { return []; };